language: node_js
node_js:
  - 0.8
services:
  - couchdb
before_script:
  - chmod -R 777 server/REST
  - cd server/REST
  - node runServer.js > run.log &
after_script:
  - curl -X GET localhost:5984/_all_dbs
  - killall -9 node
notification:
email: false