language: node_js
node_js:
  - 0.8
services:
  - couchdb
before_script:
  - chmod -R 777 server/REST
  - cd server/REST
  - node runServer.js > run.log &
  - curl -X PUT localhost:5984/myapp_test
  - curl -X GET localhost:5984/_all_dbs
  - ls
  - head FILE.txt
  - curl -d '{"docs":[{"Subject":"I like Plankton", "Author":"Rusty", "PostedDate":"2006-08-15T17:30:12-04:00", "Tags":["plankton", "baseball", "decisions"], "Body":"I decided today that I don't like baseball. I like plankton."]}' -X POST http://127.0.0.1:5984/myapp_test/_bulk_docs
after_script:
  - killall -9 node
notification:
email: false