language: node_js
node_js:
  - 0.8
services:
  - couchdb
before_script:
  - chmod -R 777 server/REST
  - cd server/REST
  - node runServer.js > run.log &
  - curl -X PUT localhost:5984/myapp_test
  - cd ~
  - cd ../..
  - ls
  - chmod -R 777 var
  - cd var/lib/couchdb/
  - ls
  - curl -d @FILE.txt -H 'Content-type: application/json' -X POST localhost:5984/myapp_test/
after_script:
  - killall -9 node
notification:
email: false