language: node_js
node_js:
  - 0.8
services:
  - couchdb
before_script:
  - chmod -R 777 server/REST
  - cd server/REST
  - node runServer.js > run.log &
  - curl -X PUT localhost:5984/myapp_test
  - curl -X GET localhost:5984/_all_dbs
  - ls
  - head FILE.txt
  - curl -X GET http://127.0.0.1:5984/myapp_test/_all_docs?include_docs=true
  - curl -H "Content-type:application/json" -d {} -X POST http://127.0.0.1:5984/myapp_test/
  - curl -X GET http://127.0.0.1:5984/myapp_test/_all_docs?include_docs=true
after_script:
  - killall -9 node
notification:
email: false